Add support for blob length for different dialects
alfasoftware/morf pull request #171
Opened 2021-08-13 09:06 UTC by pgghosh

Fixed bloblength function to use the correct db function based on the dialect.
Also added support for blob literal value evaluation using the appropriate DB function.

Changes made to MySQL, Oracle and PostGreSQL dialects only as these are the only supported dialects as of now.

2021-08-18 23:40 UTC, capgen628 requested changes

2021-08-18 23:40 UTC, capgen628 commented on morf-core/src/main/java/org/alfasoftware/morf/sql/element/BlobFieldLiteral.java
> +        super("", new BigInteger(bytes).toString(16).toUpperCase(), DataType.BLOB);
There's another super constructor that doesn't take the alias

2021-08-18 23:40 UTC, capgen628 commented on morf-core/src/main/java/org/alfasoftware/morf/sql/SqlUtils.java
> +  public static BlobFieldLiteral blobliteral(byte[] value) {
Could we just call this method blob?

2021-08-18 23:40 UTC, capgen628 commented on morf-core/src/main/java/org/alfasoftware/morf/sql/SqlUtils.java
> +  public static BlobFieldLiteral blobliteral(String value) {
Could we just call this method blob?

2021-08-18 23:40 UTC, capgen628 commented on morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlDialect.java
> +  private void checkFunctionHasSingleArgument(Function function) {
checkSingleArgument?

2021-09-07 08:28 UTC, gilleain approved these changes

2021-09-07 08:28 UTC, merged

2021-09-07 08:29 UTC, gilleain commented
Yes, looks fine.