Change the descriptions of the schemas in UpgradePathFinder to make…
alfasoftware/morf pull request #218
Opened 2022-10-24 15:31 UTC by jonknight73

…them clearer

2022-11-09 14:53 UTC, jsimlo requested changes

2022-11-09 14:53 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/metadata/SchemaHomology.java
>    }
Changes in this file are good, let's merge them.

2022-11-09 14:53 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradePathFinder.java
>      }
Let's revert these changes and wait for the consensus outcome of recently revived discussions.

2022-11-09 14:53 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradePathFinder.java
>        return true;
These fixes are good, let's merge them.

2023-08-25 10:42 UTC, harrisric commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradePathFinder.java
>        return true;
Superceded by #261 ?

2023-08-25 10:59 UTC, closed without merging

2023-08-25 11:00 UTC, jonknight73 commented
Actioned on #261