change upgrade so view definitions update based on table existing in …
alfasoftware/morf pull request #265
Opened 2023-06-19 10:07 UTC by ParkinMike

…target schema rather that in DB

2023-06-20 10:00 UTC, jsimlo requested changes

2023-06-20 10:00 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradeSchemas.java
Since we are promoting this class as an API, perhaps it would be a good idea to have a proper look at this.
Currently it is a classic stateful data holder, getters/setters, etc. Do we actually use the setters for anything?

Could we perhaps drop the setters and make the two fields `private final`, make the whole thing immutable?

And could we make the entire class `public final` as well? This will prevent mocking in tests, but that should be okay.

2023-06-20 10:00 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/LoggingSqlScriptVisitor.java
> +   * @param schemaPosition String containing scheam position.
Typo here.
Actually, let's say `schema position name`.

2023-06-20 10:00 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/ViewChangesDeploymentHelper.java
ViewChangesDeploymentHelper is effectively a piece of public API, so we cannot just add `UpgradeSchemas upgradeSchemas` to the methods. We need to keep the old methods for backwards compatibility. deprecate them, create new methods as we want them, and finally make the old methods call the new methods.

_(yeah, I know! :))_

2023-06-20 10:00 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/ViewDeploymentValidator.java
>      ViewDeploymentValidator createViewDeploymentValidator(ConnectionResources connectionResources);
Do we not need `UpgradeSchemas upgradeSchemas` here?

Ideally we would want to keep the three interfaces relatable to each other, they usually do the job together, whcih makes me wonder why this is happy without checking the schemas.

2023-06-21 17:27 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradeSchemas.java
>      }
Do we want/need this constructor?

2023-06-23 10:35 UTC, jsimlo requested changes

2023-06-23 10:35 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/ViewDeploymentValidator.java
> +    return validateExistingView(view);
This should call `validateMissingView`

2023-06-23 11:05 UTC, ParkinMike commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/ViewDeploymentValidator.java
> +    return validateExistingView(view);
updated

2023-06-23 14:34 UTC, jsimlo commented
Reviewed the [22 Code Smells](https://sonarcloud.io/project/issues?id=org.alfasoftware%3Amorf-parent&pullRequest=265&resolved=false&types=CODE_SMELL). All expected.

2023-06-23 15:16 UTC, jonknight73 commented on morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlDialect.java
> +   * @param table the talbe to add the casts.
talbe is a typo

2023-06-23 15:18 UTC, ParkinMike commented on morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlDialect.java
> +   * @param table the talbe to add the casts.
Good spot, Corrected.

2023-06-26 10:22 UTC, jsimlo approved these changes

2023-06-28 10:55 UTC, merged