Feature/morf 93 support sequence during upgrades
alfasoftware/morf pull request #315
Opened 2024-03-06 10:53 UTC by luketimmons

Support the addition and removal of schema level sequences during database upgrade steps.

2024-03-06 16:28 UTC, pgghosh commented on morf-core/src/main/java/org/alfasoftware/morf/jdbc/DatabaseMetaDataProvider.java
> +    return ImmutableMap.of();
I think the dialect specific overrides provide the required implementation.

2024-03-06 17:08 UTC, jsimlo requested changes

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/main/java/org/alfasoftware/morf/jdbc/sqlserver/SqlServerDialect.java
> +    createSequenceStatement.append(" ");
Same here with the sapce.

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/main/java/org/alfasoftware/morf/jdbc/sqlserver/SqlServerDialect.java
> +        return "current_value FROM sys.sequences WHERE name = '" + sequenceReference.getName() + "'";
I think this is wrong.
It has to be a full sub-select, including the brackets to make it a field-value again:
```
return "(SELECT current_value FROM sys.sequences WHERE name = '" + sequenceReference.getName() + "')";
````

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/main/java/org/alfasoftware/morf/jdbc/sqlserver/SqlServerDialect.java
> +    result.append(sequenceReference.getName());
This does not work with CURRENT_VALUE, only NEXT_VALUE should use it.
Move this directly to the NEXT_VALUE case.
Check what the test will spit out when used.

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/main/java/org/alfasoftware/morf/jdbc/sqlserver/SqlServerMetaDataProvider.java
> +  }
Same copy-paste

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/main/java/org/alfasoftware/morf/jdbc/sqlserver/SqlServerDialect.java
> +    result.append(sequenceReference.getName());
Oh, I see the return in CURRENT_VALUE instead of a break!
That's okay then, but you got me! :)

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/test/java/org/alfasoftware/morf/jdbc/sqlserver/TestSqlServerDialect.java
> +  }
If this was part of a bigger select, you would see the problem here.

2024-03-06 17:08 UTC, jsimlo commented on morf-sqlserver/src/test/java/org/alfasoftware/morf/jdbc/sqlserver/TestSqlServerMetaDataProvider.java
> +  }
And the same copy-paste tidy-up needed.

2024-03-07 12:43 UTC, luketimmons commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/adapt/FilteredSchema.java
>    }
I think the issue here would be that we would have two constructors with FilteredSchema(final Schema, final String...) with no way to identify if it were tables or sequences being passed in.

Potentially changing it to FilteredSchema(final Schema, final Sequence...) would be better in this case?

2024-03-07 13:04 UTC, luketimmons commented on morf-core/src/main/java/org/alfasoftware/morf/metadata/SchemaUtils.java
>    }
I think that the issue here is that as all of these methods have the same erasure if they are moved over to have Iterables as the argument. So you could have: `schema(Iterable<Table> tables)`, `schema(Iterable<View> views)`, and `schema(Iterable<Sequence> sequences)`. But if you were to call `schema()`, there would be no way to identify which method to use

2024-03-07 15:37 UTC, luketimmons commented on morf-oracle/src/main/java/org/alfasoftware/morf/jdbc/oracle/OracleMetaDataProvider.java
> +    final String sequencesSql = "SELECT sequence_name FROM ALL_SEQUENCES WHERE cache_size != 2000 AND sequence_owner=?";
This was to differentiate between sequences used to create a table's autonumber column and ones that are created independent of tables, i.e. via AddSequence. 

We appear to support adding sequences for tables in Oracle where we default the cache_size to 2000 here: https://github.com/alfasoftware/morf/pull/315/files#diff-216614a0a426b0f31568ca65c0de2d9e692d33c71320c457e280e8612b2f29aeR382

2024-03-07 16:16 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/metadata/SchemaUtils.java
>    }
Is that why we use Iterable/Collection/List for each of them? :D
Lolz. Soon we will run out of collection types.

2024-03-08 19:00 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/upgrade/adapt/FilteredSchema.java
>    }
Right, this again... ¯\_(ツ)_/¯

2024-03-08 19:17 UTC, jsimlo commented on morf-oracle/src/main/java/org/alfasoftware/morf/jdbc/oracle/OracleMetaDataProvider.java
> +    final String sequencesSql = "SELECT sequence_name FROM ALL_SEQUENCES WHERE cache_size != 2000 AND sequence_owner=?";
You might want to say that in a comment, maybe also link to org.alfasoftware.morf.jdbc.oracle.OracleDialect.createNewSequence(Table, Column).
I have completely missed that, others will too.

2024-03-08 19:26 UTC, jsimlo requested changes
Two minor changes, all good otherwise.
- comment on OracleMetaDataProvider
- simplification in SequenceBean

2024-03-11 10:28 UTC, jsimlo commented on morf-core/src/main/java/org/alfasoftware/morf/jdbc/DatabaseMetaDataProvider.java
> -  }
Note: I like this change, but it also makes the class abstract, which is a backwards-incompatible change.
That said, there were other changes already here which were backwards-incompatible too, although in less visible places.

2024-03-11 10:28 UTC, jsimlo approved these changes

2024-03-11 10:29 UTC, jsimlo commented
I have reviewed the remaining [16 New issues](https://sonarcloud.io/project/issues?id=org.alfasoftware%3Amorf-parent&pullRequest=315&resolved=false&inNewCodePeriod=true) from Sonar, they are all fine.

2024-03-11 16:54 UTC, merged